# Generated by Django 4.2.2 on 2023-10-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_cart_product_cart_quantity_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='itemsimg',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
